import type { AddOn, ComparisonRow, FaqItem, Package, PackageFeature, PackageGroup } from "./types";

/** 10% off 12 months, matching common UK fixed-fee annual billing. */
export function annualFromMonthly(monthly: number): number {
  return Math.round(monthly * 12 * 0.9);
}

const RESPONSE =
  "Same working-day reply if you write or call before 3pm on a weekday. After 3pm we reply the next working day. If we miss that, we credit £50 to your next invoice.";

const SUPPORT = "Email, phone and video, with a named accountant";

const LTD_COMPARISON: ComparisonRow = {
  yearEndAccounts: "Included",
  taxReturns: "Corporation tax (CT600) plus one director Self Assessment",
  vatSupport: "VAT returns included when you are registered",
  payrollSupport: "PAYE for up to two people",
  bookkeeping: "Quarterly bookkeeping review",
  cloudSoftware: "Xero or QuickBooks included",
  supportLevel: SUPPORT,
  responseTime: "Same working day before 3pm",
};

const SOLE_COMPARISON: ComparisonRow = {
  yearEndAccounts: "Year-end accounts for the self-employed",
  taxReturns: "Self Assessment (SA100 and business pages)",
  vatSupport: "VAT returns included when you are registered",
  payrollSupport: "PAYE for up to two people",
  bookkeeping: "Quarterly bookkeeping review",
  cloudSoftware: "Xero or QuickBooks included",
  supportLevel: SUPPORT,
  responseTime: "Same working day before 3pm",
};

export const PACKAGE_GROUPS: PackageGroup[] = [
  {
    id: "contractors-freelancers",
    name: "Contractors & Freelancers",
    summary: "Limited companies used by contractors, consultants and independent professionals.",
  },
  {
    id: "limited-companies",
    name: "Limited Companies",
    summary: "Trading companies and growing SMEs that need accounts, corporation tax and payroll.",
  },
  {
    id: "sole-traders",
    name: "Sole Traders & Self-Employed",
    summary: "Personal businesses, MTD for Income Tax support, and standalone Self Assessment.",
  },
  {
    id: "mtd",
    name: "Making Tax Digital",
    summary: "Monthly MTD packages for sole traders and landlords in scope of MTD for Income Tax.",
  },
  {
    id: "landlords",
    name: "Landlords & Property Investors",
    summary: "Let property held personally or in a company, priced by how many units you hold.",
  },
  {
    id: "medical-professional",
    name: "Medical & Professional Services",
    summary: "Locum doctors, pharmacists, opticians and similar professional practices.",
  },
  {
    id: "ecommerce-online",
    name: "E-commerce & Online Businesses",
    summary: "Online shops, marketplaces and creator businesses that sell digitally.",
  },
];

export const PACKAGE_FEATURES: PackageFeature[] = [
  {
    id: "named-accountant",
    name: "Named accountant",
    description: "You work with one Wingate accountant who knows your file, not a rotating call centre.",
  },
  {
    id: "same-day-reply",
    name: "Same-day response",
    description: RESPONSE,
  },
  {
    id: "cloud-software",
    name: "Cloud accounting software",
    description: "Xero or QuickBooks is included so you and your accountant see the same live figures.",
  },
  {
    id: "year-end",
    name: "Year-end accounts",
    description: "Statutory or self-employed accounts prepared and filed where Companies House or HMRC require them.",
  },
  {
    id: "ct600",
    name: "Corporation tax return",
    description: "CT600 prepared and submitted, with payment dates flagged in advance.",
  },
  {
    id: "self-assessment",
    name: "Self Assessment",
    description: "One personal SA100 (and usual supplementary pages for that package) prepared and filed.",
  },
  {
    id: "vat-returns",
    name: "VAT returns",
    description: "VAT returns prepared from the cloud books when the business is VAT-registered.",
  },
  {
    id: "payroll-two",
    name: "Payroll (up to two people)",
    description: "PAYE, RTI and the usual year-end payroll forms for up to two employees or directors.",
  },
  {
    id: "p11d",
    name: "P11D benefits",
    description: "P11D preparation where benefits in kind apply.",
  },
  {
    id: "bookkeeping-review",
    name: "Quarterly bookkeeping review",
    description: "We review the books each quarter, query gaps and keep the file ready for tax.",
  },
  {
    id: "confirmation-prep",
    name: "Confirmation statement preparation",
    description: "We prepare the Companies House confirmation statement. Filing the statement is an add-on.",
  },
  {
    id: "dividends",
    name: "Dividends and board minutes",
    description: "Dividend vouchers and standard board minutes for the company year.",
  },
  {
    id: "reminders",
    name: "Deadline reminders",
    description: "HMRC, Companies House and payment date reminders so filings are not left to the last week.",
  },
  {
    id: "hmrc-help",
    name: "HMRC records support",
    description: "Help with HMRC record checks, coding notices and routine correspondence on the file.",
  },
  {
    id: "status-refs",
    name: "Employment status references",
    description: "Standard contractor or locum status references when an agency or client asks for them.",
  },
  {
    id: "share-changes",
    name: "Share and officer changes",
    description: "Help with share issues or transfers and changes of company particulars.",
  },
  {
    id: "mtd-software",
    name: "MTD-ready software",
    description:
      "HMRC-recognised cloud software for digital records. MTD for Income Tax bridging from this portal is in development; your accountant still manages the filings that are live today.",
  },
  {
    id: "mtd-updates",
    name: "MTD quarterly updates",
    description: "Quarterly update support and the year-end declaration once you are in scope of MTD for Income Tax.",
  },
  {
    id: "property-accounts",
    name: "Property income accounts",
    description: "Rental income, allowable costs and finance cost restriction prepared for the year.",
  },
  {
    id: "cis",
    name: "CIS support",
    description: "Construction Industry Scheme filings where the package includes contractor or subcontractor CIS.",
  },
];

const LTD_FEATURES = [
  "named-accountant",
  "same-day-reply",
  "cloud-software",
  "year-end",
  "ct600",
  "self-assessment",
  "vat-returns",
  "payroll-two",
  "p11d",
  "bookkeeping-review",
  "confirmation-prep",
  "dividends",
  "reminders",
  "hmrc-help",
  "status-refs",
  "share-changes",
  "mtd-software",
];

const SOLE_FEATURES = [
  "named-accountant",
  "same-day-reply",
  "cloud-software",
  "year-end",
  "self-assessment",
  "vat-returns",
  "payroll-two",
  "bookkeeping-review",
  "reminders",
  "hmrc-help",
  "mtd-software",
];

const LTD_EXCLUSIONS = [
  "Companies House confirmation statement filing fee (available as an add-on)",
  "Registered office address (available as an add-on)",
  "Self Assessment for extra directors or shareholders",
  "Payroll beyond two people",
  "Company formation",
];

const SOLE_EXCLUSIONS = [
  "Corporation tax and Companies House filings (this is not a limited company package)",
  "Payroll beyond two people",
  "Specialist tax enquiry defence cover (available as an add-on)",
];

export const PACKAGES: Package[] = [
  {
    id: "contractor-complete",
    slug: "contractor-complete",
    name: "Contractor Complete",
    clientType: "Limited company contractor",
    groupId: "contractors-freelancers",
    monthlyPrice: 119,
    annualPrice: annualFromMonthly(119),
      vatNote: "",
    priceNote: "Pay 12 months at the company year start and the annual fee is 10% lower.",
    billing: "monthly",
    description:
      "One monthly fee for a contracting company: accounts, corporation tax, VAT, payroll for two, and your own Self Assessment.",
    idealFor:
      "IT, engineering and professional contractors who invoice through a limited company and want a named accountant on speed-dial.",
    highlights: [
      "Year-end accounts and CT600",
      "One director Self Assessment",
      "VAT returns when registered",
      "Payroll for up to two people",
      "Xero or QuickBooks included",
      "Named accountant",
      "Same-day reply before 3pm",
      "Dividend paperwork and confirmation statement preparation",
    ],
    featureIds: LTD_FEATURES,
    exclusions: LTD_EXCLUSIONS,
    comparison: LTD_COMPARISON,
    onboardingKind: "practice",
    isActive: true,
    featured: true,
  },
  {
    id: "freelancer-company",
    slug: "freelancer-company",
    name: "Freelancer Company",
    clientType: "Limited company freelancer",
    groupId: "contractors-freelancers",
    monthlyPrice: 113,
    annualPrice: annualFromMonthly(113),
      vatNote: "",
    priceNote: "Pay 12 months at the company year start and the annual fee is 10% lower.",
    billing: "monthly",
    description:
      "Accounts and tax for freelancers who have incorporated, with the same cloud books and named accountant as our contractor work.",
    idealFor: "Designers, consultants, developers and other independents trading through a limited company.",
    highlights: [
      "Year-end accounts and CT600",
      "One director Self Assessment",
      "VAT returns when registered",
      "Payroll for up to two people",
      "Xero or QuickBooks included",
      "Named accountant",
      "Same-day reply before 3pm",
      "Quarterly bookkeeping review",
    ],
    featureIds: LTD_FEATURES,
    exclusions: LTD_EXCLUSIONS,
    comparison: LTD_COMPARISON,
    onboardingKind: "practice",
    isActive: true,
  },
  {
    id: "small-company",
    slug: "small-company",
    name: "Small Company",
    clientType: "Limited company",
    groupId: "limited-companies",
    monthlyPrice: 113,
    annualPrice: annualFromMonthly(113),
      vatNote: "",
    priceNote: "Pay 12 months at the company year start and the annual fee is 10% lower.",
    billing: "monthly",
    description:
      "Fixed-fee accounts, corporation tax, VAT and payroll for a straightforward trading company.",
    idealFor: "Owner-managed limited companies with a simple structure and up to two people on payroll.",
    highlights: [
      "Year-end accounts and CT600",
      "One director Self Assessment",
      "VAT returns when registered",
      "Payroll for up to two people",
      "Xero or QuickBooks included",
      "Named accountant",
      "Same-day reply before 3pm",
      "Deadline reminders for HMRC and Companies House",
    ],
    featureIds: LTD_FEATURES,
    exclusions: LTD_EXCLUSIONS,
    comparison: LTD_COMPARISON,
    onboardingKind: "practice",
    isActive: true,
  },
  {
    id: "growing-business",
    slug: "growing-business",
    name: "Growing Business",
    clientType: "Larger SME / more complex company",
    groupId: "limited-companies",
    monthlyPrice: null,
    annualPrice: null,
    vatNote: "",
    priceNote: "Fee agreed after a short scoping call.",
    billing: "quote",
    description:
      "A scoped fee for companies that have outgrown a two-person payroll, hold more entities, or need extra management reporting.",
    idealFor: "SMEs with more staff, multiple companies, stock, or reporting that a standard small-company fee cannot cover.",
    highlights: [
      "Year-end accounts and corporation tax",
      "VAT and payroll scoped to the team you have",
      "Cloud software of your choice",
      "Named senior accountant",
      "Management information as agreed",
      "Same-day reply before 3pm",
      "HMRC and Companies House compliance",
      "Written fee before work starts",
    ],
    featureIds: [
      "named-accountant",
      "same-day-reply",
      "cloud-software",
      "year-end",
      "ct600",
      "vat-returns",
      "bookkeeping-review",
      "reminders",
      "hmrc-help",
    ],
    exclusions: ["Nothing is assumed until the scoped letter is signed"],
    comparison: {
      yearEndAccounts: "Included, scoped to the company",
      taxReturns: "Corporation tax; personal returns quoted if needed",
      vatSupport: "Included as scoped",
      payrollSupport: "Quoted for your headcount",
      bookkeeping: "Review frequency agreed in the letter",
      cloudSoftware: "Xero or QuickBooks",
      supportLevel: SUPPORT,
      responseTime: "Same working day before 3pm",
    },
    onboardingKind: "practice",
    isActive: true,
  },
  {
    id: "self-employed-accounts",
    slug: "self-employed-accounts",
    name: "Self-Employed Accounts",
    clientType: "Sole trader",
    groupId: "sole-traders",
    monthlyPrice: 59,
    annualPrice: annualFromMonthly(59),
      vatNote: "",
    priceNote: "Pay 12 months up front and the annual fee is 10% lower.",
    billing: "monthly",
    description:
      "Bookkeeping support, VAT if you are registered, payroll for two, and Self Assessment for a sole trader.",
    idealFor: "Self-employed contractors and tradespeople who have not incorporated and want year-round cover, not a January scramble.",
    highlights: [
      "Self Assessment prepared and filed",
      "Year-end accounts for the business",
      "VAT returns when registered",
      "Payroll for up to two people",
      "Xero or QuickBooks included",
      "Named accountant",
      "Same-day reply before 3pm",
      "Quarterly bookkeeping review",
    ],
    featureIds: SOLE_FEATURES,
    exclusions: SOLE_EXCLUSIONS,
    comparison: SOLE_COMPARISON,
    onboardingKind: "tax-return",
    isActive: true,
  },
  {
    id: "mtd-essentials",
    slug: "mtd-essentials",
    name: "MTD Comply",
    clientType: "Basic monthly subscription",
    groupId: "mtd",
    monthlyPrice: 45,
    annualPrice: annualFromMonthly(45),
    vatNote: "",
    priceNote: "The basic monthly MTD package. You keep the books; we handle setup, quarterly updates and the year-end declaration.",
    billing: "monthly",
    description:
      "Digital records software, MTD registration support and help with quarterly updates if you prefer to keep the books yourself.",
    idealFor: "Sole traders, landlords and CIS subcontractors who are comfortable with their own bookkeeping and need an accountant for MTD submissions.",
    highlights: [
      "Xero or QuickBooks for digital records",
      "Help registering for MTD for Income Tax",
      "Quarterly update support",
      "Year-end declaration support",
      "Deadline reminders",
      "Email support from a named accountant",
      "Reply within one working day",
      "Self Assessment filing for the year",
    ],
    featureIds: ["named-accountant", "cloud-software", "mtd-software", "mtd-updates", "self-assessment", "reminders"],
    exclusions: [
      "Full quarterly bookkeeping reviews (choose MTD Complete)",
      "VAT and payroll unless added",
      "Live MTD bridging from this website — that work is in development",
    ],
    comparison: {
      yearEndAccounts: "Not a full accounts package",
      taxReturns: "Self Assessment plus MTD updates",
      vatSupport: "Not included",
      payrollSupport: "Not included",
      bookkeeping: "You keep the books; we submit",
      cloudSoftware: "Xero or QuickBooks included",
      supportLevel: "Email with a named accountant",
      responseTime: "Within one working day",
    },
    onboardingKind: "tax-return",
    isActive: true,
  },
  {
    id: "mtd-full",
    slug: "mtd-full",
    name: "MTD Complete",
    clientType: "Accountant-led monthly",
    groupId: "mtd",
    monthlyPrice: 65,
    annualPrice: annualFromMonthly(65),
    vatNote: "",
    featured: true,
    billing: "monthly",
    description:
      "A named accountant reviews the books, supports VAT, payroll and CIS where needed, and keeps you on the MTD calendar.",
    idealFor: "Self-employed people and landlords who want an accountant involved all year, not only at the quarterly click.",
    highlights: [
      "Named accountant and bookkeeping reviews",
      "MTD quarterly updates and final declaration",
      "Self Assessment included",
      "VAT and payroll support when you need it",
      "CIS support where it applies",
      "Xero or QuickBooks included",
      "Same-day reply before 3pm",
      "Deadline reminders",
    ],
    featureIds: [...SOLE_FEATURES, "mtd-updates", "cis"],
    exclusions: ["Live MTD bridging from this website — that work is in development", "Payroll beyond two people"],
    comparison: {
      yearEndAccounts: "Self-employed accounts included",
      taxReturns: "Self Assessment plus MTD updates",
      vatSupport: "Supported when registered",
      payrollSupport: "Supported for up to two people",
      bookkeeping: "Regular reviews by your accountant",
      cloudSoftware: "Xero or QuickBooks included",
      supportLevel: SUPPORT,
      responseTime: "Same working day before 3pm",
    },
    onboardingKind: "tax-return",
    isActive: true,
  },
  {
    id: "personal-self-assessment",
    slug: "personal-self-assessment",
    name: "Personal Self Assessment",
    clientType: "Individual (PAYE, savings, simple SA)",
    groupId: "sole-traders",
    monthlyPrice: null,
    annualPrice: 250,
      vatNote: "",
    priceNote: "One annual fee of £250 for a personal return. Mixed income, reliefs review or HMRC letter cover uses Optimised & Protected at £325. Year-round support is £25 a month.",
    billing: "annual",
    description:
      "A named accountant prepares and files one personal Self Assessment. Use this when you do not need year-round company or sole-trader cover.",
    idealFor: "Employees with extra income, simple investment income, or anyone who only needs the annual SA100 handled.",
    highlights: [
      "SA100 prepared by an accountant",
      "Filed with HMRC after you approve it",
      "Identity checks as part of onboarding",
      "Portal messages with your accountant",
      "Deadline reminders",
      "Clear fixed fee",
    ],
    featureIds: ["named-accountant", "self-assessment", "reminders", "hmrc-help"],
    exclusions: ["Year-round bookkeeping", "VAT, payroll and company filings", "Complex supplementary pages may be quoted"],
    comparison: {
      yearEndAccounts: "Not included",
      taxReturns: "One personal Self Assessment",
      vatSupport: "Not included",
      payrollSupport: "Not included",
      bookkeeping: "Not included",
      cloudSoftware: "Not required",
      supportLevel: "Portal, email and phone",
      responseTime: "Within one working day",
    },
    onboardingKind: "tax-return",
    isActive: true,
  },
  {
    id: "landlord-personal",
    slug: "landlord-personal",
    name: "Personal Landlord",
    clientType: "Individual landlord",
    groupId: "landlords",
    monthlyPrice: 59,
    annualPrice: annualFromMonthly(59),
      vatNote: "",
    priceNote: "Fee follows the number of properties. Six or more is quoted.",
    billing: "monthly",
    description:
      "Property income, allowable costs and Self Assessment for lets held in your own name, with software included.",
    idealFor: "Buy-to-let owners who report rental income on a personal tax return.",
    highlights: [
      "Property income accounts",
      "Self Assessment with property pages",
      "Finance-cost restriction handled",
      "Xero or QuickBooks included",
      "Named accountant",
      "Same-day reply before 3pm",
      "Deadline reminders",
      "Priced by how many properties you hold",
    ],
    featureIds: [
      "named-accountant",
      "same-day-reply",
      "cloud-software",
      "property-accounts",
      "self-assessment",
      "bookkeeping-review",
      "reminders",
      "hmrc-help",
      "mtd-software",
    ],
    exclusions: ["Company accounts (use Property Company)", "Six or more properties until quoted"],
    comparison: {
      yearEndAccounts: "Property income accounts",
      taxReturns: "Self Assessment with UK property pages",
      vatSupport: "Only if VAT-registered (uncommon)",
      payrollSupport: "Not included",
      bookkeeping: "Quarterly review of rents and costs",
      cloudSoftware: "Xero or QuickBooks included",
      supportLevel: SUPPORT,
      responseTime: "Same working day before 3pm",
    },
    propertyBands: [
      { properties: "1–2", monthlyPrice: 59 },
      { properties: "3", monthlyPrice: 59 },
      { properties: "4", monthlyPrice: 68 },
      { properties: "5", monthlyPrice: 78 },
      { properties: "6+", monthlyPrice: null },
    ],
    onboardingKind: "tax-return",
    isActive: true,
  },
  {
    id: "landlord-company",
    slug: "landlord-company",
    name: "Property Company",
    clientType: "Limited company landlord",
    groupId: "landlords",
    monthlyPrice: 59,
    annualPrice: annualFromMonthly(59),
      vatNote: "",
    priceNote: "Fee follows the number of properties. Six or more is quoted.",
    billing: "monthly",
    description:
      "Company accounts, corporation tax and property bookkeeping for lets held in a limited company.",
    idealFor: "Landlords who hold property in a company and need Companies House and HMRC kept in step.",
    highlights: [
      "Year-end accounts and CT600",
      "Property bookkeeping reviews",
      "One director Self Assessment",
      "Xero or QuickBooks included",
      "Named accountant",
      "Same-day reply before 3pm",
      "Confirmation statement preparation",
      "Priced by how many properties you hold",
    ],
    featureIds: [...LTD_FEATURES, "property-accounts"],
    exclusions: LTD_EXCLUSIONS,
    comparison: {
      ...LTD_COMPARISON,
      yearEndAccounts: "Company accounts including rental activity",
      bookkeeping: "Quarterly property bookkeeping review",
    },
    propertyBands: [
      { properties: "1–2", monthlyPrice: 59 },
      { properties: "3", monthlyPrice: 78 },
      { properties: "4", monthlyPrice: 87 },
      { properties: "5", monthlyPrice: 97 },
      { properties: "6+", monthlyPrice: null },
    ],
    onboardingKind: "practice",
    isActive: true,
  },
  {
    id: "locum-medical",
    slug: "locum-medical",
    name: "Locum & Medical",
    clientType: "Locum / medical professional (limited company)",
    groupId: "medical-professional",
    monthlyPrice: 119,
    annualPrice: annualFromMonthly(119),
      vatNote: "",
    billing: "monthly",
    description:
      "The full company package, tuned for locum doctors, pharmacists, opticians and similar professionals who invoice through a company.",
    idealFor: "Medical locums and allied professionals who need status references, payroll and a named accountant who has seen this work before.",
    highlights: [
      "Year-end accounts and CT600",
      "One director Self Assessment",
      "VAT returns when registered",
      "Payroll for up to two people",
      "Status references for agencies",
      "Xero or QuickBooks included",
      "Named accountant",
      "Same-day reply before 3pm",
    ],
    featureIds: LTD_FEATURES,
    exclusions: LTD_EXCLUSIONS,
    comparison: LTD_COMPARISON,
    onboardingKind: "practice",
    isActive: true,
  },
  {
    id: "ecommerce-company",
    slug: "ecommerce-company",
    name: "Online Retail Company",
    clientType: "E-commerce limited company",
    groupId: "ecommerce-online",
    monthlyPrice: 113,
    annualPrice: annualFromMonthly(113),
      vatNote: "",
    billing: "monthly",
    description:
      "Company accounts and VAT-ready books for shops that sell online, including marketplace sellers who have incorporated.",
    idealFor: "Shopify, Amazon and similar sellers trading through a UK limited company with standard volumes.",
    highlights: [
      "Year-end accounts and CT600",
      "VAT returns when registered",
      "One director Self Assessment",
      "Payroll for up to two people",
      "Xero or QuickBooks included",
      "Named accountant",
      "Same-day reply before 3pm",
      "Quarterly bookkeeping review",
    ],
    featureIds: LTD_FEATURES,
    exclusions: [...LTD_EXCLUSIONS, "High-volume multi-channel bookkeeping may be quoted as Growing Business"],
    comparison: LTD_COMPARISON,
    onboardingKind: "practice",
    isActive: true,
  },
  {
    id: "creator-influencer",
    slug: "creator-influencer",
    name: "Creator & Influencer",
    clientType: "Creator / influencer (limited company)",
    groupId: "ecommerce-online",
    monthlyPrice: 119,
    annualPrice: annualFromMonthly(119),
      vatNote: "",
    billing: "monthly",
    description:
      "Company accounts for creators who invoice brands, take platform income and need drawings, VAT and a personal return kept tidy.",
    idealFor: "Social media, YouTube and similar creators who have incorporated or are about to.",
    highlights: [
      "Year-end accounts and CT600",
      "One director Self Assessment",
      "VAT returns when registered",
      "Payroll for up to two people",
      "Xero or QuickBooks included",
      "Named accountant",
      "Same-day reply before 3pm",
      "Help claiming genuine business costs",
    ],
    featureIds: LTD_FEATURES,
    exclusions: LTD_EXCLUSIONS,
    comparison: LTD_COMPARISON,
    onboardingKind: "practice",
    isActive: true,
  },
];

export const ADD_ONS: AddOn[] = [
  {
    id: "company-formation",
    slug: "company-formation",
    name: "Company formation",
    description:
      "We incorporate the company at Companies House, issue the first documents and hand you a company ready to bank and trade.",
    price: 150,
    vatNote: "",
    unit: "one-off",
    applicablePackageTypes: ["limited-companies", "contractors-freelancers", "medical-professional", "ecommerce-online", "landlords"],
    isActive: true,
    source: "mapped",
  },
  {
    id: "registered-office",
    slug: "registered-office",
    name: "Registered office",
    description: "Use Wingate as the company’s registered office. We scan and pass on Companies House and statutory mail.",
    price: 9.5,
      vatNote: "",
    unit: "per month",
    applicablePackageTypes: ["limited-companies", "contractors-freelancers", "medical-professional", "ecommerce-online", "landlords"],
    isActive: true,
    source: "mapped",
  },
  {
    id: "extra-director-sa",
    slug: "extra-director-sa",
    name: "Extra director Self Assessment",
    description: "A further personal tax return for an additional director or shareholder. Extra pages may be quoted if the return is complex.",
    price: 143,
      vatNote: "",
    unit: "per return",
    applicablePackageTypes: ["limited-companies", "contractors-freelancers", "medical-professional", "ecommerce-online", "landlords"],
    isActive: true,
    source: "mapped",
  },
  {
    id: "confirmation-filing",
    slug: "confirmation-filing",
    name: "Confirmation statement filing",
    description: "We submit the confirmation statement to Companies House. Preparation is already in company packages; this covers the filing itself.",
    price: 48,
      vatNote: "",
    unit: "per filing",
    applicablePackageTypes: ["limited-companies", "contractors-freelancers", "medical-professional", "ecommerce-online", "landlords"],
    isActive: true,
    source: "mapped",
  },
  {
    id: "additional-company",
    slug: "additional-company",
    name: "Additional company",
    description: "A second UK company on the same ownership, with accounts and corporation tax at a reduced extra-entity fee.",
    price: 95,
      vatNote: "",
    unit: "per month",
    applicablePackageTypes: ["limited-companies", "contractors-freelancers", "ecommerce-online", "landlords"],
    isActive: true,
    source: "wingate",
  },
  {
    id: "extra-payroll",
    slug: "extra-payroll",
    name: "Extra payroll person",
    description: "PAYE for each employee or director beyond the two already included in standard monthly packages.",
    price: 8,
      vatNote: "",
    unit: "per person / month",
    applicablePackageTypes: ["limited-companies", "contractors-freelancers", "sole-traders", "mtd", "medical-professional", "ecommerce-online"],
    isActive: true,
    source: "wingate",
  },
  {
    id: "tax-enquiry-cover",
    slug: "tax-enquiry-cover",
    name: "Tax enquiry cover",
    description: "Insurance-backed help if HMRC opens a routine enquiry into a return we have prepared. Terms are confirmed at engagement.",
    price: 15,
      vatNote: "",
    unit: "per month, from",
    applicablePackageTypes: [
      "limited-companies",
      "contractors-freelancers",
      "sole-traders",
      "mtd",
      "landlords",
      "medical-professional",
      "ecommerce-online",
    ],
    isActive: true,
    source: "wingate",
  },
  {
    id: "advisory-session",
    slug: "advisory-session",
    name: "Specialist advisory session",
    description: "A booked video session on a defined topic — incorporation, property structuring, or a one-off planning question.",
    price: 95,
      vatNote: "",
    unit: "per session",
    applicablePackageTypes: [
      "limited-companies",
      "contractors-freelancers",
      "sole-traders",
      "mtd",
      "landlords",
      "medical-professional",
      "ecommerce-online",
    ],
    isActive: true,
    source: "wingate",
  },
];

export const PACKAGE_FAQS: FaqItem[] = [
  {
    question: "Who are these packages for?",
    answer:
      "They are for UK contractors, freelancers, sole traders, landlords, locums, online sellers and small limited companies who want a published monthly fee and a named accountant. Larger or unusual structures use Growing Business, where we quote after a short call.",
  },
  {
    question: "Can I switch from my current accountant?",
    answer:
      "Yes. Once you choose a package we collect identity documents, then we write to the outgoing accountant for the records. You do not need to chase the handover yourself unless they ask you to confirm authority.",
  },
  {
    question: "What’s included in the monthly fee?",
    answer:
      "The fee covers the work listed on that package: typically accounts, the matching tax return, software, a named accountant and the response promise. Each card also lists what sits outside the fee so you can add it if you need it.",
  },
  {
    question: "Are there any hidden charges?",
    answer:
      "No surprise extras for the listed work. Confirmation statement filing, a registered office, extra payroll people, extra personal returns and formation are priced as add-ons. If a job falls outside the package we tell you the fee before we start.",
  },
  {
    question: "How do I cancel?",
    answer:
      "Write to us and we will stop the monthly fee at the next month-end after statutory work already in progress is finished or handed back. We will not trap you in a multi-year contract. Companies House and HMRC filings already started are completed or transferred with your records.",
  },
  {
    question: "Do you work with clients outside Manchester?",
    answer:
      "Yes. Wingate Accountants Limited is registered in London and we work with clients across the UK. Meetings are by video as standard; we can meet in person in London or Manchester by arrangement.",
  },
];

export const ONBOARDING_STEPS = [
  {
    n: "1",
    title: "Choose your package",
    text: "Pick the card that matches how you trade. You can add extras on the next form.",
  },
  {
    n: "2",
    title: "Complete a short onboarding form",
    text: "Name, contact details and the package (and any add-ons) you want us to set up.",
  },
  {
    n: "3",
    title: "Provide ID and business documents",
    text: "Anti-money-laundering checks: photo ID, two recent proofs of address, and company or tax records if we are taking over a file.",
  },
  {
    n: "4",
    title: "Meet your accountant",
    text: "A named Wingate accountant opens the cloud software, agrees drawings or payroll, and you start working together.",
  },
];
